### ISSUE TITLE
AfterSaveHook does not work 

### ISSUE THREAD

**Issue by tomashavner** [hendrikreimers/slug_autoupdate#2]
If your $GLOBALS['TCA']['pages']['columns']['slug']['config']['generatorOptions']['fields'] is eg [[nav_title, title]], then  "if ( !empty(array_intersect(array_keys($fieldArray), $slugGenFields)) ) {" will never trigger in Classes/Hooks/TceMain/AfterSaveHook.php

**Comment by hendrikreimers** [comment]
Thanks for the hint. Extension is obsolete / discontinued. Sorry for the late reply ;-)
